project:
  type: book

book:
  title: "ENVS-Book"
  author: "Rodney Dyer"
  date: "12/4/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - narrative_markdown.qmd
    - narrative_datatypes.qmd
    - narrative_containers.qmd
    - narrative_tidyverse.qmd
    - narrative_classic.qmd
    - narrative_ggplot.qmd
    - narrative_points.qmd
    - narrative_rasters.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand


