project:
  type: book
  output-dir: docs

book:
  title: "ENVS543-Book"
  author: "Rodney Dyer"
  date: "12/4/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - narrative_markdown.qmd
    - narrative_datatypes.qmd
    - narrative_containers.qmd
    - narrative_tidyverse.qmd
    - narrative_factors.qmd
    - narrative_joins.qmd
    - narrative_classic.qmd
    - narrative_ggplot.qmd
    - narrative_points.qmd
    - narrative_rasters.qmd
    - narrative_correlation.qmd
    - narrative_regression.qmd
    - narrative_aov.qmd
    - narrative_ordination.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand


